### ISSUE TITLE
Best fit mode for sphere markup

### ISSUE THREAD

**Issue by lassoan** [chir-set/ExtraMarkups#4]
It would be nice to add a "best fit" mode for the sphere markup that would compute least square fit sphere for all the control points. It could provide the center and radius as measurements.

**Comment by chir-set** [comment]
Hi,

Sorry for the late reply? I didn't receive email messages from github when an issue is opened.

As I said in [this](https://discourse.slicer.org/t/how-i-can-find-the-center-of-the-humeroulnar-joint-using-3d-slicer/27779) post, I could not implement this best-fit optimisation in C++.

I just pushed this module that implements the [algorithm](https://github.com/thompson318/scikit-surgery-sphere-fitting/blob/master/sksurgeryspherefitting/algorithms/sphere_fitting.py) pointed to in the above mentioned discussion.

I think that users that come up to this module can do it fairly easily, at the price of downloading and dragging a module python file into Slicer.

Regards.
