### ISSUE TITLE
Change markup (shape) tube color

### ISSUE THREAD

**Issue by mauigna06** [chir-set/ExtraMarkups#6]
It is by default blue and it cannot by changed by selecting the node in the markups module display options

**Comment by chir-set** [comment]
Unfortunately, I [couldn't](https://github.com/chir-set/SlicerExtraMarkups/blob/0e1309b4d518d903d9d53ada237fcac56c87203a/Shape/VTKWidgets/vtkSlicerShapeRepresentation3D.cxx#L643) figure out where the colour is controlled.

**Comment by chir-set** [comment]
Hi @mauigna06 ,

Commit [803b08a](https://github.com/chir-set/SlicerExtraMarkups/commit/803b08a1331426216a24f542ae81f3159e15ca79) fixes this issue. It will be available in next build.
