### ISSUE TITLE
Expose capping option of TubeShapeMarkup

### ISSUE THREAD

**Issue by mauigna06** [chir-set/ExtraMarkups#7]
Some times is useful to see the cap of the tube on 2D slices

Related [vtkTubeFilter::SetCapping](https://vtk.org/doc/nightly/html/classvtkTubeFilter.html#a86310b7bc94d16324bbbf7b65adc0b3d)

**Comment by chir-set** [comment]
You mean, you wish to visualise a capped tube instead of the open one using a switch in the markups module widget ?

**Comment by chir-set** [comment]
> Some times is useful to see the cap of the tube on 2D slices
> 
> Related [vtkTubeFilter::SetCapping](https://vtk.org/doc/nightly/html/classvtkTubeFilter.html#a86310b7bc94d16324bbbf7b65adc0b3d)

This [patch](https://github.com/chir-set/SlicerExtraMarkups/commit/be701bae01d66f950a1552804a0d303402316116) should expose this option nicely. It should be available by tomorrow.
